

upstream  backend{
    server gateaway_service:8000;
    keepalive 16;
}

upstream  minio{
    server minio:9000;
    keepalive 16;
}

upstream grafana {
    server grafana:3000;
    keepalive 16;
}

server {
    listen 80;
    server_name dom-deli.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    #listen 80;
    server_name dom-deli.ru;

    ssl_certificate /etc/letsencrypt/live/dom-deli.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dom-deli.ru/privkey.pem;

    ignore_invalid_headers off;
    client_max_body_size 0;
    
    location /api/ {
        resolver 127.0.0.11 valid=10s;

        set $backend_upstream "http://gateaway_service:8000";

        proxy_request_buffering off; 
        proxy_buffering off;
        proxy_redirect off;

        proxy_pass http://backend/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

       
    }

    location /media/{
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_request_buffering off; 
        proxy_buffering off;

        proxy_connect_timeout 300;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
        proxy_pass http://minio;
    }

    location /adminer/ {
        include /etc/nginx/conf.d/whitelist.conf;
        # allow 194.190.11.53;
        # allow 84.21.189.93;
        # allow 178.219.46.25;

        deny all;
        
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://adminer:8080;
    }


    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;  
    }
}

server {
    listen 80;
    server_name grafana.dom-deli.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name grafana.dom-deli.ru;

    ssl_certificate /etc/letsencrypt/live/dom-deli.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dom-deli.ru/privkey.pem;

    client_max_body_size 0;

    location / {
        include /etc/nginx/conf.d/whitelist.conf;

        deny all;
        proxy_pass http://grafana;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name support.dom-deli.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name support.dom-deli.ru;

    ssl_certificate /etc/letsencrypt/live/dom-deli.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dom-deli.ru/privkey.pem;

    client_max_body_size 0;

    location / {
        proxy_pass http://frontend-support:80;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}