version: '3.8'

configs:
  nginx_conf:
    file: ./nginx/config/nginx.conf
  nginx_whitelist:
    file: ./nginx/config/whitelist.conf
  backend_config:
    file: ./backend/config.yaml
  backend_private_pem:
    file: ./backend/private.pem
  backend_public_pem:
    file: ./backend/public.pem
  logstash_pipeline:
    file: ./logstash/pipeline

services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: thebugs
      POSTGRES_PASSWORD: thebugs
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_migrations:/docker-entrypoint-initdb.d  # Named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thebugs -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1  # Postgres = 1 реплика
      placement:
        constraints: [node.role == manager]  # Только на manager
      resources:
        limits:
          memory: 2G
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    volumes:
      - nginx_conf:/etc/nginx/conf.d  # Named volumes
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - app-net
    depends_on:
      - frontend
      - server

  frontend:
    image: artems18/dom-deli-frontend:latest
    deploy:
      replicas: 3  # Масштабируем фронт
      resources:
        limits:
          memory: 512M
    networks:
      - app-net

  server:
    image: artems18/dom-deli-backend:latest
    configs:
      - source: backend_config
        target: /app/config/config.yaml
      - source: backend_private_pem
        target: /app/private.pem
      - source: backend_public_pem
        target: /app/public.pem
    environment:
      APP_ENV: ${APP_ENV}
      SRV_HOST: 0.0.0.0
      PG_HOST: postgres
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_PWD: ${SMTP_PWD}
      MINIO_ENDPOINT: minio:9000
      MINIO_PUBLIC_HOST: ${IMG_URL}
      ES_HOST: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 3
      timeout: 20s
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
    networks:
      - app-net
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
    networks:
      - app-net

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: admin123
      MINIO_SECRET_KEY: admin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - app-net
    ports:
      - 9000:9000
      - 9001:9001

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ALIAS: minio
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin123
      MINIO_SECRET_KEY: admin123
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 admin123 admin123 &&
      mc mb minio/media --ignore-existing &&
      mc anonymous set public minio/media &&
      echo 'Bucket media created and public for download'
      "
    restart: "no"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_init:/usr/local/bin  # init.sh
    command: >
      bash -c "
        /usr/local/bin/docker-entrypoint.sh elasticsearch &
        sleep 30 && 
        bash /usr/local/bin/init.sh &&
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    networks:
      - app-net
    ports:
      - 9200:9200

  logstash:
    build: 
      context: ./logstash
      dockerfile: Dockerfile
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx1g
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_migrations:
  nginx_conf:
  nginx_media:
  certbot_www:
  certbot_conf:
  redis_data:
  minio_data:
  es_data:

networks:
  app-net:
    driver: overlay
    attachable: true