

services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: thebugs
      POSTGRES_PASSWORD: thebugs
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thebugs -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/share:/usr/share/nginx/html
      - ./nginx/img:/var/www/media
    ports:
      - 80:80
    depends_on:
      - frontend
      - server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    volumes:
      - ./nginx/share:/app/dist
    
    
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: ${APP_ENV}
      SRV_HOST: 0.0.0.0
      PG_HOST: postgres
      PG_PORT: 5432

    env_file:
      - .env

volumes:
  postgres_data:



